In [1]:
import pandas as pd
import numpy as np

import mosmapapi

In [2]:
# !pip install openpyxl

In [4]:
df = pd.read_excel("../data/moscow_transformed.xlsx").set_index(['ID на сайте', 'Источник'], drop=False)
df

,,ID на сайте,Источник,Название,Цена,Дата,Тип автора,Метро/Район,Адрес,lat,lng,URL,Ссылки на картинки,"Расстояние до метро, км",Этаж,Этажность здания,Вид объекта,Общая площадь
ID на сайте,Источник,,,,,,,,,,,,,,,,,
320731003,cian.ru,320731003,cian.ru,"Офис в Москва Шипиловская ул., 58к1 (25 м²)",38800,2025-08-23 02:23:27,Агентство,Шипиловская,"Шипиловская ул., 58к1",55.621211,37.745600,https://www.cian.ru/rent/commercial/320731003,['https://images.cdn-cian.ru/images/2592583348...,0.083,4.0,6.0,Офисное помещение,25.0
321876001,cian.ru,321876001,cian.ru,"Офис в Москва Ленинградский просп., 47С2 (25 м²)",31250,2025-09-25 20:21:36,Агентство,Аэропорт,"Ленинградский просп., 47С2",55.799036,37.532601,https://www.cian.ru/rent/commercial/321876001,['https://images.cdn-cian.ru/images/2631122267...,0.250,-2.0,7.0,Офисное помещение,25.0
322186790,cian.ru,322186790,cian.ru,"Офис в Москва Волгоградский просп., 2 (20 м²)",29200,2025-09-25 10:22:06,Агентство,Пролетарская,"Волгоградский просп., 2",55.731176,37.669279,https://www.cian.ru/rent/commercial/322186790,['https://images.cdn-cian.ru/images/2641248288...,0.250,6.0,16.0,Офисное помещение,20.0
321392086,cian.ru,321392086,cian.ru,Помещение свободного назначения в Москва ул. А...,32000,2025-09-02 04:23:10,Частное лицо,Бунинская Аллея,"ул. Адмирала Руднева, 20",55.540409,37.516153,https://www.cian.ru/rent/commercial/321392086,['https://images.cdn-cian.ru/images/nezhiloe-p...,0.250,3.0,7.0,Торговое / Свободного назначения,32.0
324943206,cian.ru,324943206,cian.ru,"Офис в Москва просп. Мира, 95С1 (24 м²)",44000,2025-12-11 16:28:22,Агентство,Алексеевская,"просп. Мира, 95С1",55.808002,37.635853,https://www.cian.ru/rent/commercial/324943206,['https://images.cdn-cian.ru/images/ofis-moskv...,0.167,14.0,17.0,Офисное помещение,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3987628968735107072,realty.yandex.ru,3987628968735107072,realty.yandex.ru,Офис (1200 м²),6000000,2025-09-05 16:00:52,Агентство,Шелепиха,"1-й Магистральный тупик, 5А",55.766132,37.531956,https://realty.ya.ru/offer/3987628968735107205/,NaN,11.917,4.0,8.0,Офисное помещение,1200.0
322424654,cian.ru,322424654,cian.ru,"Офис в Москва Сколковское ш., вл43 (1149 м²)",6894000,2025-10-03 08:21:53,Агентство,Кунцевская,"Сколковское ш., вл43",55.699654,37.397701,https://www.cian.ru/rent/commercial/322424654,['https://images.cdn-cian.ru/images/2650029058...,7.333,1.0,6.0,Офисное помещение,1149.0
7523548143730329600,realty.yandex.ru,7523548143730329600,realty.yandex.ru,Офис (967 м²),6769000,2025-10-22 07:59:36,Агентство,Немчиновка,"Сколковское шоссе, вл43",55.699654,37.397700,https://realty.ya.ru/offer/7523548143730329381/,['https://avatars.mds.yandex.net/get-realty-of...,18.333,3.0,6.0,Офисное помещение,967.0
322670014,cian.ru,322670014,cian.ru,"Офис в Москва Сколковское ш., вл43 (1134 м²)",7938000,2025-10-11 14:21:23,Агентство,Кунцевская,"Сколковское ш., вл43",55.699654,37.397701,https://www.cian.ru/rent/commercial/322670014,['https://images.cdn-cian.ru/images/2658570375...,7.333,2.0,6.0,Офисное помещение,1134.0
3940063262435014144,realty.yandex.ru,3940063262435014144,realty.yandex.ru,Офис (967 м²),6769000,2025-10-08 07:59:07,Агентство,Немчиновка,"Сколковское шоссе, вл43",55.699654,37.397700,https://realty.ya.ru/offer/3940063262435014084/,['https://avatars.mds.yandex.net/get-realty-of...,14.667,3.0,6.0,Офисное помещение,967.0

In [5]:
new_df = pd.read_csv("../data/moscow_super_transformed.csv")
if (len(new_df) < 10):
    new_df = pd.DataFrame()
else:
    new_df = new_df.set_index(['ID на сайте', 'Источник'])
existing_indices = [set(new_df.index), set(new_df.index)]

def get_batch_data(l: int, r: int, radius: int, id: int): # [l, r)
    global new_df
    ls = []
    for i in range(l, r):
        __ = (df.iloc[i]['ID на сайте'], df.iloc[i]['Источник'])
        if __ in existing_indices[id]:
            continue
        lat = df.iloc[i]['lat']
        lng = df.iloc[i]['lng']
        _ =pd.DataFrame(mosmapapi.get_data_radius(lat, lng,radius), index=[0])
        _['ID на сайте'] = df.iloc[i]['ID на сайте']
        _['Источник'] = df.iloc[i]['Источник']
        existing_indices[id].add(__)
        ls.append(_)
    if len(ls) == 0:
        return None
    return pd.concat(ls).set_index(['ID на сайте', 'Источник'])

def get_all_data(batch_size: int, l: int, r: int):
    global new_df
    for i in range(l, r, batch_size):
        dt1 = get_batch_data(i, min(i + batch_size, r), 300, 0)
        dt2 = get_batch_data(i, min(i + batch_size, r), 600, 1)
        if dt1 is None or dt2 is None:
            continue
        _ = pd.concat([dt1, dt2.drop(['district_price', 'district_name'], axis=1)], axis=1)
        new_df = pd.concat([new_df, _], axis=0)
        new_df.to_csv("../data/moscow_super_transformed.csv")

In [6]:
existing_indices

[{(325113244, 'cian.ru'),
  (323203178, 'cian.ru'),
  (323573244, 'cian.ru'),
  (323281388, 'cian.ru'),
  (8660284132703721472, 'realty.yandex.ru'),
  (3086750354037853184, 'realty.yandex.ru'),
  (323168366, 'cian.ru'),
  (321149121, 'cian.ru'),
  (6819069171518081024, 'realty.yandex.ru'),
  (325265827, 'cian.ru'),
  (321389462, 'cian.ru'),
  (323351575, 'cian.ru'),
  (320915497, 'cian.ru'),
  (321960386, 'cian.ru'),
  (4121682813316516864, 'realty.yandex.ru'),
  (3086799692142487040, 'realty.yandex.ru'),
  (320448588, 'cian.ru'),
  (324775102, 'cian.ru'),
  (321280430, 'cian.ru'),
  (323162150, 'cian.ru'),
  (321878137, 'cian.ru'),
  (319367485, 'cian.ru'),
  (321391222, 'cian.ru'),
  (7080657422337197056, 'realty.yandex.ru'),
  (324552914, 'cian.ru'),
  (325158265, 'cian.ru'),
  (8660284132706432000, 'realty.yandex.ru'),
  (325182999, 'cian.ru'),
  (324639802, 'cian.ru'),
  (7517866235140775936, 'realty.yandex.ru'),
  (324645707, 'cian.ru'),
  (322640033, 'cian.ru'),
  (322876529, 'cian.ru'),
  (324152898, 'cian.ru'),
  (321506352, 'cian.ru'),
  (322434845, 'cian.ru'),
  (324856058, 'cian.ru'),
  (2108370138117195008, 'realty.yandex.ru'),
  (325257410, 'cian.ru'),
  (321896655, 'cian.ru'),
  (322279944, 'cian.ru'),
  (322471959, 'cian.ru'),
  (3255862766659222016, 'realty.yandex.ru'),
  (325146987, 'cian.ru'),
  (324238500, 'cian.ru'),
  (3965285094498903040, 'realty.yandex.ru'),
  (323642978, 'cian.ru'),
  (323927778, 'cian.ru'),
  (321960446, 'cian.ru'),
  (660076875171869440, 'realty.yandex.ru'),
  (319890450, 'cian.ru'),
  (321003286, 'cian.ru'),
  (320912909, 'cian.ru'),
  (324977830, 'cian.ru'),
  (3799907618229260800, 'realty.yandex.ru'),
  (8660284132702824448, 'realty.yandex.ru'),
  (324093177, 'cian.ru'),
  (320000595, 'cian.ru'),
  (324701253, 'cian.ru'),
  (322483335, 'cian.ru'),
  (4934127428783991808, 'realty.yandex.ru'),
  (325759333673215232, 'realty.yandex.ru'),
  (4071103118089015808, 'realty.yandex.ru'),
  (3255678710597649920, 'realty.yandex.ru'),
  (324035526, 'cian.ru'),
  (3965285094500514816, 'realty.yandex.ru'),
  (320737779, 'cian.ru'),
  (321552088, 'cian.ru'),
  (322436479, 'cian.ru'),
  (322767014, 'cian.ru'),
  (3941543084096285184, 'realty.yandex.ru'),
  (323862810, 'cian.ru'),
  (3965285094528337920, 'realty.yandex.ru'),
  (322759863, 'cian.ru'),
  (322758857, 'cian.ru'),
  (325275940, 'cian.ru'),
  (321618120, 'cian.ru'),
  (306948989166340672, 'realty.yandex.ru'),
  (321357405, 'cian.ru'),
  (3941543084012123136, 'realty.yandex.ru'),
  (321168240, 'cian.ru'),
  (323518310, 'cian.ru'),
  (321168396, 'cian.ru'),
  (6819069281515114496, 'realty.yandex.ru'),
  (322389227, 'cian.ru'),
  (2361989381428098048, 'realty.yandex.ru'),
  (321030224, 'cian.ru'),
  (320800795, 'cian.ru'),
  (3255678710657739776, 'realty.yandex.ru'),
  (3673425669977824256, 'realty.yandex.ru'),
  (321724717, 'cian.ru'),
  (319967193, 'cian.ru'),
  (321994121, 'cian.ru'),
  (320553979, 'cian.ru'),
  (3965285094498843136, 'realty.yandex.ru'),
  (8660284132704494592, 'realty.yandex.ru'),
  (322110662, 'cian.ru'),
  (6029649816087990272, 'realty.yandex.ru'),
  (325113247, 'cian.ru'),
  (3941757984976572928, 'realty.yandex.ru'),
  (322526848, 'cian.ru'),
  (3941757984977252864, 'realty.yandex.ru'),
  (321648721, 'cian.ru'),
  (7554998452, 'avito.ru'),
  (318333664, 'cian.ru'),
  (323527384, 'cian.ru'),
  (324686217, 'cian.ru'),
  (321745797, 'cian.ru'),
  (324107521, 'cian.ru'),
  (322095942, 'cian.ru'),
  (3606804499664268800, 'realty.yandex.ru'),
  (321466988, 'cian.ru'),
  (325131902, 'cian.ru'),
  (321048249, 'cian.ru'),
  (320773230, 'cian.ru'),
  (324659222, 'cian.ru'),
  (320695311, 'cian.ru'),
  (3086776659646958080, 'realty.yandex.ru'),
  (324679876, 'cian.ru'),
  (322731613, 'cian.ru'),
  (2575346277739589120, 'realty.yandex.ru'),
  (3086745183441405952, 'realty.yandex.ru'),
  (3087408763731165184, 'realty.yandex.ru'),
  (3793567139278212096, 'realty.yandex.ru'),
  (5114134638346442752, 'realty.yandex.ru'),
  (7555533309, 'avito.ru'),
  (320489755, 'cian.ru'),
  (323409152, 'cian.ru'),
  (320713028, 'cian.ru'),
  (324541464, 'cian.ru'),
  (324815873, 'cian.ru'),
  (322586193, 'cian.ru'),
  (3965285094498841088, 'realty.yandex.ru'),
  (320535528, 'cian.ru'),
  (3405278847343203840, 'realty.yandex.ru'),
  (324099025, 'cian.ru'),
  (5227646640187716608, 'realty.yandex.ru'),
  (325032631, 'cian.ru'),
  (7495507292, 'avito.ru'),
  (325269754, 'cian.ru'),
  (6151351842510253056, 'realty.yandex.ru'),
  (323959724, 'cian.ru'),
  (324470618, 'cian.ru'),
  (324127256, 'cian.ru'),
  (8617973498467957760, 'realty.yandex.ru'),
  (322439708, 'cian.ru'),
  (319574280, 'cian.ru'),
  (324498222, 'cian.ru'),
  (3051474335861101056, 'realty.yandex.ru'),
  (325203695, 'cian.ru'),
  (8004581521109135360, 'realty.yandex.ru'),
  (324509385, 'cian.ru'),
  (323446065, 'cian.ru'),
  (321070374, 'cian.ru'),
  (321313508, 'cian.ru'),
  (7502296691568023552, 'realty.yandex.ru'),
  (322913153, 'cian.ru'),
  (321206140, 'cian.ru'),
  (321178023, 'cian.ru'),
  (320633686, 'cian.ru'),
  (324480603, 'cian.ru'),
  (8660284132706345984, 'realty.yandex.ru'),
  (324070060, 'cian.ru'),
  (8660284132705566720, 'realty.yandex.ru'),
  (2361989404502444032, 'realty.yandex.ru'),
  (324554193, 'cian.ru'),
  (325146990, 'cian.ru'),
  (321072867, 'cian.ru'),
  (320551844, 'cian.ru'),
  (322923948, 'cian.ru'),
  (325089077, 'cian.ru'),
  (320505211, 'cian.ru'),
  (3965285094498874880, 'realty.yandex.ru'),
  (323694419, 'cian.ru'),
  (5227725131901900800, 'realty.yandex.ru'),
  (1901015578463897088, 'realty.yandex.ru'),
  (324651500, 'cian.ru'),
  (322633813, 'cian.ru'),
  (324397601, 'cian.ru'),
  (7576364428042762240, 'realty.yandex.ru'),
  (320725081, 'cian.ru'),
  (324803707, 'cian.ru'),
  (320021280, 'cian.ru'),
  (324133483, 'cian.ru'),
  (322112568, 'cian.ru'),
  (346082229460120832, 'realty.yandex.ru'),
  (322449560, 'cian.ru'),
  (2108370138113643008, 'realty.yandex.ru'),
  (3965285094498817024, 'realty.yandex.ru'),
  (320596932, 'cian.ru'),
  (325083162, 'cian.ru'),
  (324402434, 'cian.ru'),
  (5227593921583466496, 'realty.yandex.ru'),
  (322327673, 'cian.ru'),
  (244099181403371200, 'realty.yandex.ru'),
  (324998187, 'cian.ru'),
  (6819069280708762624, 'realty.yandex.ru'),
  (323702498, 'cian.ru'),
  (322122619, 'cian.ru'),
  (3941758948096243200, 'realty.yandex.ru'),
  (314365810, 'cian.ru'),
  (324393608, 'cian.ru'),
  (321054332, 'cian.ru'),
  (320998554, 'cian.ru'),
  (321084071, 'cian.ru'),
  (323369663, 'cian.ru'),
  (8660284132704409600, 'realty.yandex.ru'),
  (324864181, 'cian.ru'),
  (322721506, 'cian.ru'),
  (324372490, 'cian.ru'),
  (323151001, 'cian.ru'),
  (7053515440140807168, 'realty.yandex.ru'),
  (320771852, 'cian.ru'),
  (7554649673, 'avito.ru'),
  (321588452, 'cian.ru'),
  (321874537, 'cian.ru'),
  (323600707, 'cian.ru'),
  (320451474, 'cian.ru'),
  (324880100, 'cian.ru'),
  (3965285094498814976, 'realty.yandex.ru'),
  (323265649, 'cian.ru'),
  (320583208, 'cian.ru'),
  (3086826186788952064, 'realty.yandex.ru'),
  (3086805001189507072, 'realty.yandex.ru'),
  (322686568, 'cian.ru'),
  (322723748, 'cian.ru'),
  (321186279, 'cian.ru'),
  (322207838, 'cian.ru'),
  (321719279, 'cian.ru'),
  (3941543084004977152, 'realty.yandex.ru'),
  (325127787, 'cian.ru'),
  (321016735, 'cian.ru'),
  (324059991, 'cian.ru'),
  (324023845, 'cian.ru'),
  (324403247, 'cian.ru'),
  (2361989379624518144, 'realty.yandex.ru'),
  (7547469589, 'avito.ru'),
  (5227725131902558208, 'realty.yandex.ru'),
  (321522701, 'cian.ru'),
  (321067660, 'cian.ru'),
  (325161538, 'cian.ru'),
  (321851834, 'cian.ru'),
  (325031175, 'cian.ru'),
  (321759428, 'cian.ru'),
  (3087406282270873088, 'realty.yandex.ru'),
  (324924802, 'cian.ru'),
  (5483092735358571520, 'realty.yandex.ru'),
  (6819069301066118144, 'realty.yandex.ru'),
  (3086824586620739072, 'realty.yandex.ru'),
  (323409428, 'cian.ru'),
  (6329189682737712128, 'realty.yandex.ru'),
  (321608583, 'cian.ru'),
  (322155143, 'cian.ru'),
  (323696653, 'cian.ru'),
  (3087408789468771840, 'realty.yandex.ru'),
  (8232352984612284416, 'realty.yandex.ru'),
  (320710885, 'cian.ru'),
  (320628586, 'cian.ru'),
  (2793718051887429120, 'realty.yandex.ru'),
  (319631413, 'cian.ru'),
  (324814379, 'cian.ru'),
  (323150161, 'cian.ru'),
  (320749903, 'cian.ru'),
  (5228459417828390912, 'realty.yandex.ru'),
  (7538797846, 'avito.ru'),
  (324897343, 'cian.ru'),
  (323845543, 'cian.ru'),
  (321364881, 'cian.ru'),
  (324991560, 'cian.ru'),
  (3965285094524796928, 'realty.yandex.ru'),
  (6819069278936562688, 'realty.yandex.ru'),
  (323426709, 'cian.ru'),
  (2733450895063452160, 'realty.yandex.ru'),
  (7289995120732888064, 'realty.yandex.ru'),
  (324848196, 'cian.ru'),
  (3372048850312404992, 'realty.yandex.ru'),
  (2344553746359556096, 'realty.yandex.ru'),
  (3965285094498934784, 'realty.yandex.ru'),
  (325075045, 'cian.ru'),
  (192505607768518400, 'realty.yandex.ru'),
  (321191036, 'cian.ru'),
  (320275348, 'cian.ru'),
  (324991773, 'cian.ru'),
  (325275567, 'cian.ru'),
  (321790376, 'cian.ru'),
  (323788743, 'cian.ru'),
  (323139290, 'cian.ru'),
  (320294467, 'cian.ru'),
  (3090898769006269952, 'realty.yandex.ru'),
  (322774878, 'cian.ru'),
  (324725963, 'cian.ru'),
  (324430638, 'cian.ru'),
  (3673425663799349760, 'realty.yandex.ru'),
  (3965285094498872832, 'realty.yandex.ru'),
  (324725868, 'cian.ru'),
  (325256238, 'cian.ru'),
  (2361982467828973056, 'realty.yandex.ru'),
  (322882565, 'cian.ru'),
  (306948989166346496, 'realty.yandex.ru'),
  (324351724, 'cian.ru'),
  (7534731564, 'avito.ru'),
  (915583364433553536, 'realty.yandex.ru'),
  (324612562, 'cian.ru'),
  (7677323227855159296, 'realty.yandex.ru'),
  (323407118, 'cian.ru'),
  (324735774, 'cian.ru'),
  (320108539, 'cian.ru'),
  (319740969, 'cian.ru'),
  (324766798, 'cian.ru'),
  (325128234, 'cian.ru'),
  (306948989166287808, 'realty.yandex.ru'),
  (1736082285859492096, 'realty.yandex.ru'),
  (3984986711660227072, 'realty.yandex.ru'),
  (321457598, 'cian.ru'),
  (320821262, 'cian.ru'),
  (324390123, 'cian.ru'),
  (322267309, 'cian.ru'),
  (324144698, 'cian.ru'),
  (321651171, 'cian.ru'),
  (7517866235141816320, 'realty.yandex.ru'),
  (7425624539306777600, 'realty.yandex.ru'),
  (306948989166376320, 'realty.yandex.ru'),
  (2361989379536721920, 'realty.yandex.ru'),
  (320031876, 'cian.ru'),
  (324736469, 'cian.ru'),
  (7518381301, 'avito.ru'),
  (5838106955260986368, 'realty.yandex.ru'),
  (321049821, 'cian.ru'),
  (323832507, 'cian.ru'),
  (320597148, 'cian.ru'),
  (323655115, 'cian.ru'),
  (325144113, 'cian.ru'),
  (323953754, 'cian.ru'),
  (8226940054235705344, 'realty.yandex.ru'),
  (306948989166342784, 'realty.yandex.ru'),
  (320495780, 'cian.ru'),
  (320709069, 'cian.ru'),
  (323946865, 'cian.ru'),
  (3965285094499588096, 'realty.yandex.ru'),
  (322717470, 'cian.ru'),
  (8427502013113704448, 'realty.yandex.ru'),
  (324546126, 'cian.ru'),
  (3051474281718069760, 'realty.yandex.ru'),
  (323415625, 'cian.ru'),
  (322928206, 'cian.ru'),
  (244099984370712512, 'realty.yandex.ru'),
  (320261414, 'cian.ru'),
  (3450671260059648000, 'realty.yandex.ru'),
  (324029608, 'cian.ru'),
  (323747522, 'cian.ru'),
  (322967321, 'cian.ru'),
  (323160245, 'cian.ru'),
  (321294019, 'cian.ru'),
  (324227711, 'cian.ru'),
  (320760711, 'cian.ru'),
  (324017496, 'cian.ru'),
  (3965285094499586048, 'realty.yandex.ru'),
  (1099302674047524992, 'realty.yandex.ru'),
  (318668670, 'cian.ru'),
  (3086746975311339008, 'realty.yandex.ru'),
  (8660284132701728768, 'realty.yandex.ru'),
  (322700410, 'cian.ru'),
  (322683729, 'cian.ru'),
  (322840442, 'cian.ru'),
  (7547573876, 'avito.ru'),
  (324532279, 'cian.ru'),
  (3941543084012250112, 'realty.yandex.ru'),
  (7556947359, 'avito.ru'),
  (7579554793, 'avito.ru'),
  (322390973, 'cian.ru'),
  (320576843, 'cian.ru'),
  (4510880785027502080, 'realty.yandex.ru'),
  (3112999785047188992, 'realty.yandex.ru'),
  (3965285094528223232, 'realty.yandex.ru'),
  (8302265147550152704, 'realty.yandex.ru'),
  (325074197, 'cian.ru'),
  (321921137, 'cian.ru'),
  (323900028, 'cian.ru'),
  (320823351, 'cian.ru'),
  (324828136, 'cian.ru'),
  (320740308, 'cian.ru'),
  (324996674, 'cian.ru'),
  (7562443272, 'avito.ru'),
  (322949673, 'cian.ru'),
  (322192502, 'cian.ru'),
  (3941543084012188160, 'realty.yandex.ru'),
  (322280455, 'cian.ru'),
  (323140586, 'cian.ru'),
  (325119122, 'cian.ru'),
  (321030154, 'cian.ru'),
  (321066938, 'cian.ru'),
  (320598967, 'cian.ru'),
  (325163145, 'cian.ru'),
  (321734610, 'cian.ru'),
  (320667173, 'cian.ru'),
  (323571088, 'cian.ru'),
  (321160631, 'cian.ru'),
  (325193667, 'cian.ru'),
  (324636342, 'cian.ru'),
  (322727861, 'cian.ru'),
  (324320701, 'cian.ru'),
  (323426914, 'cian.ru'),
  (320067621, 'cian.ru'),
  (7404290536130923520, 'realty.yandex.ru'),
  (945634382163523072, 'realty.yandex.ru'),
  (325131889, 'cian.ru'),
  (7343538772343916544, 'realty.yandex.ru'),
  (7534522955, 'avito.ru'),
  (323174697, 'cian.ru'),
  (319780761, 'cian.ru'),
  (321851829, 'cian.ru'),
  (3941757984976541184, 'realty.yandex.ru'),
  (321960387, 'cian.ru'),
  (3965285094500538880, 'realty.yandex.ru'),
  (324946987, 'cian.ru'),
  (5227593921579746304, 'realty.yandex.ru'),
  (320349898, 'cian.ru'),
  (320512687, 'cian.ru'),
  (321158709, 'cian.ru'),
  (323375991, 'cian.ru'),
  (322510310, 'cian.ru'),
  (323562603, 'cian.ru'),
  (322851253, 'cian.ru'),
  (322408295, 'cian.ru'),
  (320304695, 'cian.ru'),
  (323492270, 'cian.ru'),
  (321878970, 'cian.ru'),
  (321611954, 'cian.ru'),
  (3086798201136303104, 'realty.yandex.ru'),
  (7517866235141814272, 'realty.yandex.ru'),
  (323310643, 'cian.ru'),
  (324813368, 'cian.ru'),
  (324803132, 'cian.ru'),
  (322318990, 'cian.ru'),
  (3965285094499743232, 'realty.yandex.ru'),
  (8427502013113679872, 'realty.yandex.ru'),
  (321246574, 'cian.ru'),
  (325176512, 'cian.ru'),
  (325277640, 'cian.ru'),
  (323152379, 'cian.ru'),
  (320367692, 'cian.ru'),
  (324872595, 'cian.ru'),
  (321628654, 'cian.ru'),
  (323600896, 'cian.ru'),
  (3965285094526582784, 'realty.yandex.ru'),
  (321594837, 'cian.ru'),
  (6912306082656647168, 'realty.yandex.ru'),
  (3116915239174381056, 'realty.yandex.ru'),
  (324107712, 'cian.ru'),
  (5733952308786621440, 'realty.yandex.ru'),
  (320097922, 'cian.ru'),
  (324851371, 'cian.ru'),
  (324791680, 'cian.ru'),
  (325266679, 'cian.ru'),
  (324949453, 'cian.ru'),
  (325158266, 'cian.ru'),
  (7589924689, 'avito.ru'),
  (8427502013113738240, 'realty.yandex.ru'),
  (323376261, 'cian.ru'),
  (6939372906429431808, 'realty.yandex.ru'),
  (325147094, 'cian.ru'),
  (7239522370813248512, 'realty.yandex.ru'),
  (323858065, 'cian.ru'),
  (325003422, 'cian.ru'),
  (7535326093, 'avito.ru'),
  (325146988, 'cian.ru'),
  (834281980401883136, 'realty.yandex.ru'),
  (324804370, 'cian.ru'),
  (324982042, 'cian.ru'),
  (325089064, 'cian.ru'),
  (324316711, 'cian.ru'),
  (321619018, 'cian.ru'),
  (324339394, 'cian.ru'),
  (322260682, 'cian.ru'),
  (3965285094524729856, 'realty.yandex.ru'),
  (320315637, 'cian.ru'),
  (319283447, 'cian.ru'),
  (323392085, 'cian.ru'),
  (320452039, 'cian.ru'),
  (3086805662379748864, 'realty.yandex.ru'),
  (3087412038619747840, 'realty.yandex.ru'),
  (323665739, 'cian.ru'),
  (320519328, 'cian.ru'),
  (320816587, 'cian.ru'),
  (3965285094499679232, 'realty.yandex.ru'),
  (325257419, 'cian.ru'),
  (2361982442841474048, 'realty.yandex.ru'),
  (320481036, 'cian.ru'),
  (322870604, 'cian.ru'),
  (8856076337843025920, 'realty.yandex.ru'),
  (321357125, 'cian.ru'),
  (320579001, 'cian.ru'),
  (320819833, 'cian.ru'),
  (321118987, 'cian.ru'),
  (324742475, 'cian.ru'),
  (8083511258116902912, 'realty.yandex.ru'),
  (4777675775676092416, 'realty.yandex.ru'),
  (320596562, 'cian.ru'),
  (3328666814366576128, 'realty.yandex.ru'),
  (321389232, 'cian.ru'),
  (321746048, 'cian.ru'),
  (321186062, 'cian.ru'),
  (318838149, 'cian.ru'),
  (322638131, 'cian.ru'),
  (319660907, 'cian.ru'),
  (322025378, 'cian.ru'),
  (325234051, 'cian.ru'),
  (324196652, 'cian.ru'),
  (322647663, 'cian.ru'),
  (321158643, 'cian.ru'),
  (319065579, 'cian.ru'),
  (320897329, 'cian.ru'),
  (322335935, 'cian.ru'),
  (324822764, 'cian.ru'),
  (323598588, 'cian.ru'),
  (322905429, 'cian.ru'),
  (324067827, 'cian.ru'),
  (325168098, 'cian.ru'),
  (321185996, 'cian.ru'),
  (323253835, 'cian.ru'),
  (321042073, 'cian.ru'),
  (325197515, 'cian.ru'),
  (320468897, 'cian.ru'),
  (325146980, 'cian.ru'),
  (322393905, 'cian.ru'),
  (320573221, 'cian.ru'),
  (325188133, 'cian.ru'),
  (325263521, 'cian.ru'),
  (7404290536130917376, 'realty.yandex.ru'),
  (3087409646797326848, 'realty.yandex.ru'),
  (322236193, 'cian.ru'),
  (324844520, 'cian.ru'),
  (320897784, 'cian.ru'),
  (323799274, 'cian.ru'),
  (325172814, 'cian.ru'),
  (321217244, 'cian.ru'),
  (323389658, 'cian.ru'),
  (324144597, 'cian.ru'),
  (320898605, 'cian.ru'),
  (321851843, 'cian.ru'),
  (321283672, 'cian.ru'),
  (322250844, 'cian.ru'),
  (7567072086303291392, 'realty.yandex.ru'),
  (5201387770577629184, 'realty.yandex.ru'),
  (320460933, 'cian.ru'),
  (322439690, 'cian.ru'),
  (3965285094498818048, 'realty.yandex.ru'),
  (325049324, 'cian.ru'),
  (322652090, 'cian.ru'),
  (320727302, 'cian.ru'),
  (322832652, 'cian.ru'),
  (324013558, 'cian.ru'),
  (3965285094500696064, 'realty.yandex.ru'),
  (3965285094531169792, 'realty.yandex.ru'),
  (321960458, 'cian.ru'),
  (320980470, 'cian.ru'),
  (325145742, 'cian.ru'),
  (324144704, 'cian.ru'),
  (320593006, 'cian.ru'),
  (320461996, 'cian.ru'),
  (3965285094527355904, 'realty.yandex.ru'),
  (1419183387920034048, 'realty.yandex.ru'),
  (320584057, 'cian.ru'),
  (324638838, 'cian.ru'),
  (322827116, 'cian.ru'),
  (322483347, 'cian.ru'),
  (321070481, 'cian.ru'),
  (325173326, 'cian.ru'),
  (5680755582743153664, 'realty.yandex.ru'),
  (324637341, 'cian.ru'),
  (325096355, 'cian.ru'),
  (3086779438420981760, 'realty.yandex.ru'),
  (324301383, 'cian.ru'),
  (2108370138117338112, 'realty.yandex.ru'),
  (321616913, 'cian.ru'),
  (2361982364704150016, 'realty.yandex.ru'),
  (322151663, 'cian.ru'),
  (322356756, 'cian.ru'),
  (3965285094501469184, 'realty.yandex.ru'),
  (2818428305209270784, 'realty.yandex.ru'),
  (320254334, 'cian.ru'),
  (5227593921576108032, 'realty.yandex.ru'),
  (323649427, 'cian.ru'),
  (323087782, 'cian.ru'),
  (322727343, 'cian.ru'),
  (324762012, 'cian.ru'),
  (8660284132703576064, 'realty.yandex.ru'),
  (321952571, 'cian.ru'),
  (323765070, 'cian.ru'),
  (319807103, 'cian.ru'),
  (4777675775680855040, 'realty.yandex.ru'),
  (320505916, 'cian.ru'),
  (323568107, 'cian.ru'),
  (8303086569397168128, 'realty.yandex.ru'),
  (323194348, 'cian.ru'),
  (8660284132703634432, 'realty.yandex.ru'),
  (322868926, 'cian.ru'),
  (322161029, 'cian.ru'),
  (324601476, 'cian.ru'),
  (324021233, 'cian.ru'),
  (321131564, 'cian.ru'),
  (323910346, 'cian.ru'),
  (7567073849773289472, 'realty.yandex.ru'),
  (324650970, 'cian.ru'),
  (321186288, 'cian.ru'),
  (321186299, 'cian.ru'),
  (474292427704933632, 'realty.yandex.ru'),
  (7555407605, 'avito.ru'),
  (321304220, 'cian.ru'),
  (3941543084004859904, 'realty.yandex.ru'),
  (322150319, 'cian.ru'),
  (316665408, 'cian.ru'),
  (322003469, 'cian.ru'),
  (7697756682408886272, 'realty.yandex.ru'),
  (319582381, 'cian.ru'),
  (322863273, 'cian.ru'),
  (3941757984976508928, 'realty.yandex.ru'),
  (324082975, 'cian.ru'),
  (322763549, 'cian.ru'),
  (321977084, 'cian.ru'),
  (320245231, 'cian.ru'),
  (3051474284148718080, 'realty.yandex.ru'),
  (323314361, 'cian.ru'),
  (7589010455, 'avito.ru'),
  (321256052, 'cian.ru'),
  (3965285094522945024, 'realty.yandex.ru'),
  (320473645, 'cian.ru'),
  (321511634, 'cian.ru'),
  (320957034, 'cian.ru'),
  (306948989166370432, 'realty.yandex.ru'),
  (7053956965884665856, 'realty.yandex.ru'),
  (321498567, 'cian.ru'),
  (320595444, 'cian.ru'),
  (323616017, 'cian.ru'),
  (320094813, 'cian.ru'),
  (320180079, 'cian.ru'),
  (321574235, 'cian.ru'),
  (320815587, 'cian.ru'),
  (322204705, 'cian.ru'),
  (321406586, 'cian.ru'),

In [7]:
new_df

,,district_name,n_buildings_300m,n_living_buildings_300m,n_flats_300m,min_bc_distance_300m,mean_bc_distance_300m,traffic1_300m,traffic2_300m,traffic3_300m,traffic4_300m,...,Ветаптеки и ветклиники_600,Магазины цветов_600,"Прачечные, химчистки_600",Детские игровые залы_600,Религия_600,"Пиццерии, суши, столовые_600","Пекарни, кофейни_600","Кафе, бары, рестораны_600",Социальные_600,Банки_600
ID на сайте,Источник,,,,,,,,,,,,,,,,,,,,,
320731003,cian.ru,Зябликово,38.0,14.0,3610.0,0.0,123.500000,8176.0,6091.0,1557.0,1713.0,...,8,8,7,0,0,3,7,11,8,1
321876001,cian.ru,Хорошевский,54.0,15.0,1287.0,0.0,82.666667,9392.0,38428.0,1513.0,11424.0,...,3,12,9,0,0,10,34,30,5,2
322186790,cian.ru,Таганский,44.0,22.0,3234.0,9.0,178.200000,8304.0,19462.0,2032.0,6787.0,...,10,17,15,0,1,11,29,29,10,2
321392086,cian.ru,Бутово Южное,23.0,8.0,1831.0,10.0,10.000000,4194.0,4593.0,2101.0,3820.0,...,1,6,3,0,1,4,7,9,5,0
324943206,cian.ru,Останкинский,46.0,30.0,3647.0,4.0,117.000000,7146.0,24972.0,4008.0,17350.0,...,6,8,15,0,1,16,27,29,10,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324035526,cian.ru,Гольяново,20.0,14.0,4010.0,157.0,157.000000,5896.0,4311.0,12891.0,588.0,...,2,7,5,0,0,8,13,18,0,0
320759234,cian.ru,Зюзино,22.0,10.0,861.0,48.0,133.000000,1018.0,40175.0,5384.0,28894.0,...,2,5,2,0,1,6,1,6,2,1
322153703,cian.ru,Останкинский,15.0,2.0,97.0,27.0,27.000000,1508.0,5622.0,2812.0,4538.0,...,2,4,3,6,0,5,15,44,4,0
320725081,cian.ru,Даниловский,92.0,21.0,196.0,56.0,204.000000,80.0,8059.0,213.0,8587.0,...,3,15,9,0,2,26,39,50,0,4
3086748598555571200,realty.yandex.ru,Чертаново Южное,37.0,NaN,NaN,0.0,173.166667,0.0,59415.0,588.0,21119.0,...,1,4,1,0,1,4,8,21,2,2

In [8]:
df.iloc[795][['lat', 'lng']]

lat    55.814593
lng    37.693785
Name: (323409428, cian.ru), dtype: object

In [9]:
mosmapapi.api_call_analytic(55.814593, 37.7456, 300)

{'latitude': 55.814593,
 'longitude': 37.7456,
 'district_name': 'Метрогородок',
 'price': {'district_price': '283200',
  'district_price_room1': '293800',
  'district_price_room2': '277400',
  'district_price_room3': '274800',
  'district_price_room4': '243600'},
 'orgs': {'2': {'group_name': 'Медицина', 'count': 0},
  '3': {'group_name': 'Стоматологии', 'count': 0},
  '4': {'group_name': 'Аптеки, оптики', 'count': 0},
  '5': {'group_name': 'Салоны красоты', 'count': 0},
  '6': {'group_name': 'Бани, сауны', 'count': 0},
  '7': {'group_name': 'Фитнес-центры, тренажерные', 'count': 0},
  '8': {'group_name': 'Супермаркеты', 'count': 0},
  '9': {'group_name': 'Гипермаркеты', 'count': 0},
  '10': {'group_name': 'Продуктовые магазины', 'count': 0},
  '11': {'group_name': 'Алкомаркеты, магазины пива', 'count': 0},
  '13': {'group_name': 'Школы, лицеи, гимназии', 'count': 0},
  '14': {'group_name': 'Детские сады', 'count': 0},
  '15': {'group_name': 'Колледжи, институты', 'count': 0},
  '16': {'group_name': 'Студенческие общежития', 'count': 0},
  '17': {'group_name': 'Торговые центры, моллы', 'count': 0},
  '18': {'group_name': 'Бизнес-центры', 'count': 0},
  '19': {'group_name': 'Пункты выдачи товаров', 'count': 0},
  '20': {'group_name': 'Ветаптеки и ветклиники', 'count': 0},
  '21': {'group_name': 'Магазины цветов', 'count': 0},
  '22': {'group_name': 'Прачечные, химчистки', 'count': 0},
  '23': {'group_name': 'Детские игровые залы', 'count': 0},
  '24': {'group_name': 'Религия', 'count': 0},
  '26': {'group_name': 'Пиццерии, суши, столовые', 'count': 0},
  '28': {'group_name': 'Пекарни, кофейни', 'count': 0},
  '29': {'group_name': 'Кафе, бары, рестораны', 'count': 0},
  '30': {'group_name': 'Социальные', 'count': 0},
  '31': {'group_name': 'Банки', 'count': 0}},
 'zone': [{'name': 'Строений', 'value': 20},
  {'name': 'Жилых домов', 'value': 3},
  {'name': 'Квартир', 'value': 1008},
  {'name': 'Средний возраст домов', 'value': '0 лет'},
  {'name': 'Стоимость метра жилья вторичка', 'value': '368600 руб.'}],
 'bcenters': [],
 'metro_exits': {'1159': {'name': 'Бульвар Рокоссовского',
   'numb': '1',
   'lng': '37.73750',
   'lat': '55.81572'}},
 'traffic1': 0,
 'traffic2': 12,
 'traffic3': 0,
 'traffic4': 0}

In [10]:
mosmapapi.get_data_radius(55.621211, 37.7456, 300)

{'district_name': 'Зябликово',
 'n_buildings_300m': 38,
 'n_living_buildings_300m': 14,
 'n_flats_300m': 3610,
 'min_bc_distance_300m': np.int64(0),
 'mean_bc_distance_300m': np.float64(123.5),
 'traffic1_300m': 8176,
 'traffic2_300m': 6091,
 'traffic3_300m': 1557,
 'traffic4_300m': 1713,
 'Медицина_300': 3,
 'Стоматологии_300': 3,
 'Аптеки, оптики_300': 4,
 'Салоны красоты_300': 13,
 'Бани, сауны_300': 0,
 'Фитнес-центры, тренажерные_300': 1,
 'Супермаркеты_300': 0,
 'Гипермаркеты_300': 0,
 'Продуктовые магазины_300': 10,
 'Алкомаркеты, магазины пива_300': 3,
 'Школы, лицеи, гимназии_300': 2,
 'Детские сады_300': 3,
 'Колледжи, институты_300': 0,
 'Студенческие общежития_300': 0,
 'Торговые центры, моллы_300': 0,
 'Бизнес-центры_300': 1,
 'Пункты выдачи товаров_300': 8,
 'Ветаптеки и ветклиники_300': 0,
 'Магазины цветов_300': 1,
 'Прачечные, химчистки_300': 2,
 'Детские игровые залы_300': 0,
 'Религия_300': 0,
 'Пиццерии, суши, столовые_300': 0,
 'Пекарни, кофейни_300': 1,
 'Кафе, бары, рестораны_300': 1,
 'Социальные_300': 3,
 'Банки_300': 0,
 'district_price': '281700'}

In [12]:
get_all_data(10, 0, 4500)

C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])
C:\Users\misha\AppData\Local\Temp\ipykernel_6384\716075108.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(ls).set_index(['ID на сайте', 'Источник'])

KeyboardInterrupt: