In [26]:
import pandas as pd
import numpy as np
from geopy.distance import EARTH_RADIUS


def haversin(theta):
    # https://en.wikipedia.org/wiki/Versine#Haversine
    return (1 - np.cos(theta)) / 2.0


def haversine_2D_mat(data1, data2):
    """Попарное расстояние между точками двух выборок"""
    lats1, lons1 = data1['lat'].values, data1['lon'].values
    phis1, lambs1 = np.radians(lats1).reshape(-1, 1), np.radians(lons1).reshape(-1, 1)

    lats2, lons2 = data2['lat'].values, data2['lon'].values
    phis2, lambs2 = np.radians(lats2).reshape(-1, 1), np.radians(lons2).reshape(-1, 1)

    deltas_lats = phis1 - phis2.T
    deltas_lons = lambs1 - lambs2.T

    cos_phis1 = np.cos(phis1)
    cos_phis2 = np.cos(phis2)
    a = haversin(deltas_lats) + cos_phis1 * cos_phis2.T * haversin(deltas_lons)

    vec_dist = 2 * EARTH_RADIUS * np.arcsin(np.sqrt(a))
    return vec_dist * 1000

In [42]:
from glob import glob

df = pd.concat([
    pd.read_csv(file)
    for file in glob("data/geocoding_ya/*.csv")
], axis=0)[["lat", "lon"]].dropna()
df.shape

(47706, 2)

In [43]:
point_df = df.sample(1)
point_df

            lat        lon
5703  55.673459  37.577443

In [44]:
df

            lat        lon
3     55.625578  37.606392
4     55.625578  37.606392
5     55.625578  37.606392
6     55.625578  37.606392
7     55.625578  37.606392
...         ...        ...
7194  55.657776  37.620317
7197  55.657101  37.621272
7198  55.651736  37.618845
7199  55.655788  37.620557
7200  55.655120  37.620263

[47706 rows x 2 columns]

In [45]:
M = haversine_2D_mat(point_df, df)

R = 500
point_df.loc[M <= R]

(1, 47706)

In [93]:
import time

def f(x):
    time.sleep(x)
    return 2 * x + 1

def g(y):
    time.sleep(y)
    return 3 * y ** 2 - 2

In [94]:
%%time
f_val = f(12)
g_val = g(8)
f_val + g_val

CPU times: total: 0 ns
Wall time: 20 s

215

In [95]:
import asyncio

async def f(x):
    await asyncio.sleep(x)
    return 2 * x + 1

async def g(y):
    await asyncio.sleep(y)
    return 3 * y ** 2 - 2

In [96]:
start = time.time()
f_val, g_val = await asyncio.gather(f(12), g(8))
print(f_val + g_val)
print(time.time() - start)

215
11.99815845489502

In [ ]:
async def API(lat, lon, R):
    ...

async def yandex_base(lat, lon, R, rubricks):
    ...

api_data, ya_data = await asyncio.gather(API(...), yandex_base(...))
df = pd.concat([api_data, ya_data])

In [ ]:
[
    1) [кафе, бары, бильярд] -> "кафе_бары_бильярд" = 8
    2) [кафе] -> "кафе" = 2
    3) [бары] -> "бары" = 4
    4) [бильярд] -> "бильярд" = 2
]