In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv("../data/data_transformed_part3.csv")
data.head()

,Unnamed: 0,ID на сайте,Источник,Цена,Дата,Тип автора,Город,Метро/Район,Адрес,Описание,...,lng,URL,Ссылки на картинки,"Расстояние до метро, км",Вид объекта,Общая площадь,Этаж,Этажность здания,Цена / м2,Log(Цена)
0,9,7433930500,avito.ru,321301.0,2025-06-10 17:34:54,Агентство,Электросталь,NaN,"Московская обл., Электросталь, ул. Корешкова, 3","НАЗВАНИЕ: Торговая площадь, 96.4 м²\n\nОПИСАНИ...",...,38.447391,https://www.avito.ru/elektrostal/kommercheskay...,https://80.img.avito.st/image/1/1.YWRzmra5zY1F...,NaN,Торговое / Свободное назначение,96.4,2.0,NaN,3332.997925,12.680137
1,10,117287608663576318,realty.yandex.ru,195703.0,2025-06-11 07:59:45,Агентство,Химки,Подрезково,"Авиационная улица, 8",НАЗВАНИЕ: Офис (182.9 м²)\n\nОПИСАНИЕ: Помещен...,...,37.408940,https://realty.ya.ru/offer/117287608663576318/,https://avatars.mds.yandex.net/get-realty-offe...,15.583,Офис / Здание,182.9,4.0,8.0,1070.000000,12.184359
2,11,315859923,cian.ru,260000.0,2025-06-27 20:24:38,Агентство,Люберцы,Некрасовка,"Зенино ЖК Самолет мкр, проезд Некрасовский, 7",НАЗВАНИЕ: Торговая площадь в Московская област...,...,37.951207,https://www.cian.ru/rent/commercial/315859923,https://images.cdn-cian.ru/images/2446134629-1...,2.000,Торговое / Свободное назначение,118.0,1.0,14.0,2203.389831,12.468441
3,14,7544327122,avito.ru,180000.0,2025-07-21 13:38:36,Частное лицо (фильтр),Видное,NaN,"Московская обл., Ленинский г.о., д. Коробово, ...","НАЗВАНИЕ: Торговая площадь, 78.8 м²\n\nОПИСАНИ...",...,37.822164,https://www.avito.ru/vidnoe/kommercheskaya_ned...,https://00.img.avito.st/image/1/1.koliQLa5PmBU...,NaN,Торговое / Свободное назначение,78.8,1.0,NaN,2284.263959,12.100718
4,16,319629521,cian.ru,360000.0,2025-07-10 16:24:26,Агентство,Подольск,NaN,"просп. Юных Ленинцев, 1/2А",НАЗВАНИЕ: Торговая площадь в Московская област...,...,37.559550,https://www.cian.ru/rent/commercial/319629521,https://images.cdn-cian.ru/images/2557237384-1...,NaN,Торговое / Свободное назначение,180.0,1.0,1.0,2000.000000,12.793862

In [ ]:
data["Тип автора"] = data["Тип автора"].replace({
    "Частное лицо (фильтр)": "Частное лицо"
})

data["Москва?"] = (data["Город"] == "Москва").astype(int)

In [3]:
data

,Unnamed: 0,ID на сайте,Источник,Цена,Дата,Тип автора,Город,Метро/Район,Адрес,Описание,...,URL,Ссылки на картинки,"Расстояние до метро, км",Вид объекта,Общая площадь,Этаж,Этажность здания,Цена / м2,Log(Цена),Москва?
0,9,7433930500,avito.ru,321301.0,2025-06-10 17:34:54,Агентство,Электросталь,NaN,"Московская обл., Электросталь, ул. Корешкова, 3","НАЗВАНИЕ: Торговая площадь, 96.4 м²\n\nОПИСАНИ...",...,https://www.avito.ru/elektrostal/kommercheskay...,https://80.img.avito.st/image/1/1.YWRzmra5zY1F...,NaN,Торговое / Свободное назначение,96.40,2.0,NaN,3332.997925,12.680137,0
1,10,117287608663576318,realty.yandex.ru,195703.0,2025-06-11 07:59:45,Агентство,Химки,Подрезково,"Авиационная улица, 8",НАЗВАНИЕ: Офис (182.9 м²)\n\nОПИСАНИЕ: Помещен...,...,https://realty.ya.ru/offer/117287608663576318/,https://avatars.mds.yandex.net/get-realty-offe...,15.583,Офис / Здание,182.90,4.0,8.0,1070.000000,12.184359,0
2,11,315859923,cian.ru,260000.0,2025-06-27 20:24:38,Агентство,Люберцы,Некрасовка,"Зенино ЖК Самолет мкр, проезд Некрасовский, 7",НАЗВАНИЕ: Торговая площадь в Московская област...,...,https://www.cian.ru/rent/commercial/315859923,https://images.cdn-cian.ru/images/2446134629-1...,2.000,Торговое / Свободное назначение,118.00,1.0,14.0,2203.389831,12.468441,0
3,14,7544327122,avito.ru,180000.0,2025-07-21 13:38:36,Частное лицо,Видное,NaN,"Московская обл., Ленинский г.о., д. Коробово, ...","НАЗВАНИЕ: Торговая площадь, 78.8 м²\n\nОПИСАНИ...",...,https://www.avito.ru/vidnoe/kommercheskaya_ned...,https://00.img.avito.st/image/1/1.koliQLa5PmBU...,NaN,Торговое / Свободное назначение,78.80,1.0,NaN,2284.263959,12.100718,0
4,16,319629521,cian.ru,360000.0,2025-07-10 16:24:26,Агентство,Подольск,NaN,"просп. Юных Ленинцев, 1/2А",НАЗВАНИЕ: Торговая площадь в Московская област...,...,https://www.cian.ru/rent/commercial/319629521,https://images.cdn-cian.ru/images/2557237384-1...,NaN,Торговое / Свободное назначение,180.00,1.0,1.0,2000.000000,12.793862,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7736,19990,7465545600,avito.ru,300000.0,2025-06-18 20:06:31,Частное лицо,Видное,NaN,"Московская обл., Ленинский г.о., д. Сапроново,...","НАЗВАНИЕ: Свободного назначения, 98.4 м²\n\nОП...",...,https://www.avito.ru/vidnoe/kommercheskaya_ned...,https://30.img.avito.st/image/1/1.Exh8cba5v_FK...,NaN,Торговое / Свободное назначение,98.40,1.0,NaN,3048.780488,12.611541,0
7737,19991,319044778,cian.ru,1200009.0,2025-07-11 04:24:18,Агентство,Красногорск,Мякинино,"Ильинское ш., 1а","НАЗВАНИЕ: Офис в Московская область, Красногор...",...,https://www.cian.ru/rent/commercial/319044778,https://images.cdn-cian.ru/images/2537231127-1...,7.333,Офис / Здание,590.00,2.0,9.0,2033.913559,13.997840,0
7738,19993,7360733108,avito.ru,37000.0,2025-06-09 13:33:12,Агентство,Королев,NaN,"Московская обл., Королёв, пр-т Космонавтов, 47/16","НАЗВАНИЕ: Торговая площадь, 41.18 м²\n\nОПИСАН...",...,https://www.avito.ru/korolev/kommercheskaya_ne...,https://50.img.avito.st/image/1/1.SrPMoLa55lr6...,NaN,Торговое / Свободное назначение,41.18,2.0,NaN,898.494415,10.518700,0
7739,19994,7556996843,avito.ru,500000.0,2025-07-15 09:03:31,Агентство,Балашиха,Никольское,"Московская обл., Балашиха, мкр-н Никольско-Арх...",НАЗВАНИЕ: ПСН 2 мин мцд Никольская\n\nОПИСАНИЕ...,...,https://www.avito.ru/balashiha/kommercheskaya_...,https://50.img.avito.st/image/1/1.3xc9Hba5c_4L...,0.100,Торговое / Свободное назначение,310.80,1.0,NaN,1608.751609,13.122365,0
7740,19998,7470880264,avito.ru,123600.0,2025-06-27 17:00:19,Агентство,Одинцово,Одинцово,"Московская обл., Одинцовский г.о., Одинцово, С...",НАЗВАНИЕ: Сдам помещение свободного назначения...,...,https://www.avito.ru/odintsovo/kommercheskaya_...,https://50.img.avito.st/image/1/1.43Lczra5T5vq...,0.900,Торговое / Свободное назначение,41.20,1.0,NaN,3000.000000,11.724814,0

In [4]:
data.to_csv("../data/data_transformed_part3.csv")