In [22]:
!python --version

Python 3.13.11

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("geo_data.csv")
df.head()

,Unnamed: 0,address,name_ru,avg_rating,rubrics,lat,lon,geocode_status
0,0,"г. Москва, пр-кт Волгоградский, д. 46 Б",Стратегия Оценки,5.0,Оценочная компания;Экспертиза;Строительная экс...,NaN,NaN,not_found
1,1,",Москва, Западный административный округ, райо...",One and Double,1.0,Кофейня,NaN,NaN,not_found
2,2,"Адрес: Московская область, Люберецкий район, Б...",Газмагистраль,5.0,"АГНС, АГЗС, АГНКС",NaN,NaN,not_found
3,3,Москва,Экспериментальный квартал,5.0,Достопримечательность,55.625578,37.606392,success
4,4,Москва,ОкнаДел,5.0,Окна;Изготовление витражей;Реставрационная мас...,55.625578,37.606392,success

In [3]:
df = df.dropna(subset = ["lat"])
df = df[df["address"] != "Москва"]
df.head()

,Unnamed: 0,address,name_ru,avg_rating,rubrics,lat,lon,geocode_status
16,16,"Москва, 1-й Автозаводский проезд, 4к1",Абрикосик,2.0,Массажный салон,55.703938,37.656436,success
17,17,"Москва, 1-й Автозаводский проезд, 5",Чайхана Азия,2.0,Кафе,55.704831,37.657289,success
18,18,"Москва, 1-й Автозаводский проезд, 5",RenarDance,5.0,Школа танцев,55.704831,37.657289,success
20,20,"Москва, 1-й Амбулаторный проезд, 8с1",Колледж автомобильного транспорта № 9,5.0,Колледж,55.811594,37.532844,success
21,21,"Москва, 1-й Балтийский переулок, 3/25",ХуанХэ,5.0,Ресторан;Кафе,55.810501,37.518897,success

In [4]:
df = df.drop("geocode_status", axis = 1)

In [19]:
from geopy.distance import EARTH_RADIUS


def haversin(theta):
    return (1 - np.cos(theta)) / 2.0

def haversine_2D_mat(data1, data2):
    lats1, lons1 = data1['lat'].values, data1['lon'].values
    phis1, lambs1 = np.radians(lats1).reshape(-1, 1), np.radians(lons1).reshape(-1, 1)

    lats2, lons2 = data2['lat'].values, data2['lon'].values
    phis2, lambs2 = np.radians(lats2).reshape(-1, 1), np.radians(lons2).reshape(-1, 1)

    deltas_lats = phis1 - phis2.T
    deltas_lons = lambs1 - lambs2.T

    cos_phis1 = np.cos(phis1)
    cos_phis2 = np.cos(phis2)
    a = haversin(deltas_lats) + cos_phis1 * cos_phis2.T * haversin(deltas_lons)

    vec_dist = 2 * EARTH_RADIUS * np.arcsin(np.sqrt(a))
    return vec_dist * 1000

In [20]:
def get_list(lat, lon, R, rub):
    point_df = pd.DataFrame({"lat": [lat], "lon": [lon]})
    ls = haversine_2D_mat(point_df, df)[0]
    r = df.loc[ls <= R, "rubrics"]
    rub_split = r.str.split(";").dropna()
    rub_split = rub_split.apply(lambda x: set(x))
    lst = {}
    for sub in rub_split:
        for a in rub:
            fl = False
            for x in a:
                if x in sub:
                    fl = True
            if fl:
                lst["_".join(a)] = lst.get("_".join(a), 0) + 1
    return lst

In [18]:
%%time
R = 5000
rub_lst = get_list(55.810501, 37.518897, R, [["Ресторан", "Кафе"], ["Кафе"], ["Ресторан"]])
rub_lst

CPU times: total: 125 ms
Wall time: 122 ms

{'Ресторан_Кафе': 2691, 'Кафе': 1756, 'Ресторан': 1568}

In [9]:
from collections import Counter
from itertools import chain

st = Counter(chain.from_iterable(df["rubrics"].str.split(";")))
st = Counter({k: v for k, v in st.items() if v >= 30})

In [10]:
st

Counter({'Кафе': 1756,
         'Ресторан': 1568,
         'Салон красоты': 1518,
         'Магазин продуктов': 1032,
         'Ногтевая студия': 1004,
         'Супермаркет': 884,
         'Парикмахерская': 765,
         'Быстрое питание': 716,
         'Бар, паб': 714,
         'Кофейня': 680,
         'Косметология': 575,
         'Медцентр, клиника': 479,
         'Стоматологическая клиника': 450,
         'Салон бровей и ресниц': 410,
         'Магазин одежды': 396,
         'Доставка еды и обедов': 388,
         'Массажный салон': 366,
         'Пункт выдачи': 364,
         'Автосервис, автотехцентр': 363,
         'Гостиница': 338,
         'Аптека': 306,
         'Магазин подарков и сувениров': 302,
         'Банкетный зал': 293,
         'Фитнес-клуб': 286,
         'Магазин алкогольных напитков': 283,
         'Магазин цветов': 279,
         'Магазин хозтоваров и бытовой химии': 273,
         'Кондитерская': 273,
         'Пиццерия': 268,
         'Кофе с собой': 241,
         'Барбершоп': 240,
         'Пекарня': 233,
         'Шиномонтаж': 232,
         'Диагностический центр': 228,
         'Магазин парфюмерии и косметики': 224,
         'Дополнительное образование': 222,
         'Банк': 221,
         'Спортивный клуб, секция': 221,
         'Торговый центр': 220,
         'Эпиляция': 207,
         'Кальян-бар': 205,
         'Автомойка': 203,
         'Детский сад, ясли': 196,
         'Доставка цветов и букетов': 188,
         'Спа-салон': 188,
         'Суши-бар': 187,
         'Товары для дома': 184,
         'Ремонт телефонов': 183,
         'Спортивный, тренажёрный зал': 177,
         'Центр развития ребёнка': 175,
         'Компьютерный ремонт и услуги': 175,
         'Товары для мобильных телефонов': 167,
         'Стоматологическая поликлиника': 164,
         'Фотоуслуги': 162,
         'Магазин обуви': 157,
         'Магазин табака и курительных принадлежностей': 156,
         'Магазин электроники': 154,
         'Медицинская лаборатория': 152,
         'Салон оптики': 148,
         'Магазин мебели': 147,
         'Бассейн': 145,
         'Общеобразовательная школа': 144,
         'Магазин автозапчастей и автотоваров': 141,
         'Зоомагазин': 137,
         'Копировальный центр': 136,
         'Детейлинг': 134,
         'Полиграфические услуги': 126,
         'Ветеринарная клиника': 125,
         'Курсы и мастер-классы': 124,
         'Магазин верхней одежды': 122,
         'Музей': 120,
         'Юридические услуги': 118,
         'Поликлиника для взрослых': 118,
         'Школа танцев': 116,
         'Спортивная школа': 116,
         'Магазин бытовой техники': 116,
         'Развлекательный центр': 115,
         'Православный храм': 114,
         'Магазин пива': 114,
         'Турагентство': 114,
         'Магазин мяса, колбас': 110,
         'Вейп-шоп': 109,
         'Клуб для детей и подростков': 108,
         'Автосалон': 107,
         'Ювелирный магазин': 105,
         'Столовая': 104,
         'Зуботехническая лаборатория': 102,
         'Компьютерный магазин': 100,
         'Товары для праздника': 99,
         'Химчистка': 99,
         'Театр': 98,
         'Магазин галантереи и аксессуаров': 97,
         'Учебный центр': 96,
         'Мебель для кухни': 96,
         'Караоке-клуб': 94,
         'АЗС': 94,
         'Ветеринарная аптека': 93,
         'Магазин сантехники': 93,
         'Парк культуры и отдыха': 93,
         'Зоосалон, зоопарикмахерская': 92,
         'Магазин кулинарии': 92,
         'Больница для взрослых': 88,
         'Ремонт одежды': 86,
         'Спортивный комплекс': 85,
         'Магазин детской одежды': 85,
         'Ремонт обуви': 84,
         'Автошкола': 84,
         'Организация и проведение детских праздников': 84,
         'Мебель на заказ': 83,
         'Контактные линзы': 82,
         'Типография': 82,
         'Магазин фиксированной цены': 81,
         'Ателье по пошиву одежды': 81,
         'Шугаринг': 80,
         'Визажисты, стилисты': 78,
         'Организация мероприятий': 78,
         'Детские игрушки и игры': 77,
         'Обучение мастеров для салонов красоты': 77,
         'Строительный магазин': 77,
         'Спортивная одежда и обувь': 76,
         'Спортивный магазин': 76,
         'Ноутбуки и планшеты': 74,
         'Хостел': 73,
         'Детская поликлиника': 73,
         'Автомобильные грузоперевозки': 72,
         'Кузовной ремонт': 72,
         'Солярий': 72,
         'Магазин рыбы и морепродуктов': 72,
         'Курьерские услуги': 71,
         'Магазин канцтоваров': 70,
         'Гинекологическая клиника': 69,
         'Агентство недвижимости': 69,
         'Сауна': 68,
         'Курсы иностранных языков': 67,
         'Магазин суши и азиатских продуктов': 65,
         'Бизнес-центр': 64,
         'Мягкая мебель': 64,
         'Магазин сумок и чемоданов': 64,
         'Ночной клуб': 63,
         'Книжный магазин': 63,
         'Музыкальное образование': 63,
         'Нотариусы': 62,
         'Культурный центр': 62,
         'Салон связи': 62,
         'Печати и штампы': 62,
         'Спортбар': 60,
         'Студия йоги': 60,
         'Кинотеатр': 59,
         'Фитопродукция, БАДы': 58,
         'Двери': 58,
         'Аренда площадок для культурно-массовых мероприятий': 57,
         'Школа искусств': 56,
         'Шины и диски': 56,
         'Металлоремонт': 55,
         'Ювелирная мастерская': 55,
         'Мотошкола': 55,
         'Магазин белья и купальников': 55,
         'Жилой комплекс': 54,
         'Достопримечательность': 54,
         'Концертный зал': 54,
         'Магазин чая': 53,
         'Продажа автомобилей с пробегом': 53,
         'Оздоровительный центр': 53,
         'Детский магазин': 53,
         'Товары для отдыха и туризма': 52,
         'Строительные и отделочные работы': 52,
         'Спортивный инвентарь и оборудование': 52,
         'Магазин часов': 52,
         'Ремонт бытовой техники': 51,
         'Выставочный центр': 50,
         'Магазин посуды': 50,
         'Ветеринарная лаборатория': 49,
         'Туроператор': 49,
         'Магазин бижутерии': 49,
         'Ломбард': 49,
         'Грузовые авиаперевозки': 48,
         'Баня': 48,
         'Студия автотюнинга': 47,
         'Квесты': 47,
         'Прачечная': 47,
         'Коррекция зрения': 46,
         'Строительная компания': 46,
         'Корпусная мебель': 46,
         'Страховая компания': 46,
         'Магазин ткани': 45,
         'Бюро переводов': 45,
         'Товары для интерьера': 45,
         'Продуктовый рынок': 45,
         'Тату-салон': 45,
         'Художественная мастерская': 44,
         'Кейтеринг': 44,
         'Торты на заказ': 44,
         'Коворкинг': 43,
         'Керамическая плитка': 43,
         'Спортивное питание': 43,
         'Магазин детской обуви': 43,
         'Автоаксессуары': 42,
         'Автостёкла': 42,
         'Ремонт велосипедов': 42,
         'Ремонт часов': 41,
         'Центр повышения квалификации': 40,
         'Ремонт двигателей': 40,
         'Продажа и аренда коммерческой недвижимости': 40,
         'Библиотека': 40,
         'Багетные изделия': 40,
         'Продуктовый гипермаркет': 40,
         'Бытовые услуги': 39,
         'Остановка общественного транспорта': 39,
         'Окна': 39,
         'ВУЗ': 39,
         'Товары для творчества и рукоделия': 39,
         'Логопеды': 39,
         'Веломагазин': 39,
         'Железнодорожная станция': 38,
         'Железнодорожные и авиабилеты': 38,
         'Ремонт АКПП': 38,
         'Магазин овощей и фруктов': 38,
         'Страхование автомобилей': 37,
         'Дизайн интерьеров': 37,
         'Ремонт очков': 37,
         'Студия перманентного макияжа': 37,
         'Интернет-провайдер': 36,
         'Товары для здоровья': 36,
         'Клуб досуга': 36,
         'Выкуп автомобилей': 36,
         'Адвокаты': 36,
         'Ремонт аудиотехники и видеотехники': 35,
         'Фотостудия': 35,
         'Женская консультация': 35,
         'Творческий коллектив': 35,
         'Жанровая скульптура': 35,
         'Магазин постельных принадлежностей': 34,
         'Экскурсии': 34,
         'Шторы, карнизы': 33,
         'Медицинская реабилитация': 33,
         'Художественный салон': 33,
         'Ортопедический салон': 33,
         'Компьютерный клуб': 33,
         'Магазин электротоваров': 33,
         'IT-компания': 32,
         'Табачная продукция оптом': 32,
         'Детская больница': 32,
         'Напольные покрытия': 31,
         'Антикафе': 31,
         'Колледж': 30,
         'Оборудование и материалы для салонов красоты': 30,
         'Оператор сотовой связи': 30,
         'Спортивное объединение': 30,
         'Учебная литература': 30,
         'Музыкальный магазин': 30,
         'Мебельная фабрика': 30,
         'Бронирование гостиниц': 30,
         'Детская площадка': 30})